kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-test-account-binding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: role-test-account
  apiGroup: rbac.authorization.k8s.io
